pickups = ["I thought happiness started with an H. Why does mine start with U?",
"If kissing is spreading germs… How about we start an epidemic?","If my heart were to fly, your soul would be my airport",
"You may fall from the sky, you may fall from a tree, but the best way to fall… is in love with me.",
"Can I have your picture so I can show Santa what I want for Christmas?"
,
"Are you a keyboard? Because you’re my type!","Baby, if you were a fruit you’d be a fineapple.",
"What do you and your shower have in common? they both get wet when I turn them on",
"I’m no weatherman but I know gonna get to get 7 inches tonight.",
"They say nothing lasts forever—so would you be my nothing",
"Even in zero gravity, I would still fall for you!",
"Hey, tie your shoes! I don’t want you falling for anyone else",
"You spend so much time in my mind, I should charge you rent.",
"Do you have any room for an extra tongue in your mouth?",
"The doctor said I’m sick because I’m lacking vitamin U",
"Kiss me if I’m wrong, but dinosaurs still exist, right?",
"Would you call out my name so I can tell my friends I’ve been called by an angel",
"If I had a dollar for every time I thought of you, I’d have one dollar. Because you never leave my mind.",
"The only problem with your lips is that they’re too far away from mine.",
"Does your name start with “C” because I can C us together",
"Roses are red. Violets are blue. You be the six. I’ll be the nine.","Are you my homework? Cause I’m not doing you, but I definitely should be.",
"Are your legs made of Nutella? Because I’d love to spread them.",
"How much longer until I get to the part where you give me your number?",
"Do I know you? ‘Cause you look a lot like my next lover.",
"I’m lost. Can you give me directions to your heart?",
"Aside from playing with my heart, what do you do for a living?",
"Let’s play Titanic. You’ll be the iceberg and I’ll go down.",
"Want to save water by showering together?",
"If you are a Youtube Ad I wont skip you",
"You wanna be my hope but p is silent",
"Are you christmas bcoz I wanna merry you",
"Do you know what is christmas,if you jingle my bells its christmas",
"There's sideview,rearview, and what else? i loview",
"You owe me a drink bcoz when i saw u i dropped mine",
"Is your father a thief, cause he stole the stars in the sky and put it in ur eyes",
"I bet you $20 you're gonna turn me down.",
"I wish I was one of your tears, so I could be in your eye, run down your cheek, and on your lips and does go it down more",
"Are you good at catching? Cause I think I am falling in love with you!",
"I went to a bakery to get a cutiepie like you but apparently they werent selling",
"If a thousand painters worked for a thousand years, they could not create a work of art as beaitiful like u",
"Me without you is like a shoe without laces,a Sentence without spaces",
"If i had to choose between breathing or loving you, I would say I love you with my last breath",
"If i were a traffic light i would turn red everytime u pass by just so i can stare at u more",
"Everyone wants to steal my penis can i hide it inside you",
"lets play barbie I'll be ken and you be the box that comes with it",
"Im giving a dare send me a friend request",
"I've been dating you in my head for 10 years",
":crystal_ball:I see me in your future",
"I believe in following my dreams. Can I have your Instagram?",
"I can’t see you right now, but I bet you look great.",
"Can I save you in my phone as love of my life?",
"Is it just the WiFi? Or am I totally feeling a connection?",
"Do you believe in love at first text or should I text you again?",
"Are you Siri? Because you autocomplete me.",
"I guarantee you, I’m not flirting with you. I’m just being extra nice to someone who’s extra attractive.",
"Call me your COVID-19 vaccine,coz all I want is to keep you safe",
"You're my Bluetooth device. Thanks for pairing with me! ",
"I was trying to send you something cute, but I don’t think I can fit in this text box",
"Do you have an extra parachute? ‘Coz I’m falling for you",
"It’s not fair. You spoil me with expensive gifts every time we meet—butterflies and a smile",
"I hope you’re planning to stay. I don’t want you to fly back to heaven without me",
" Which sweetener would you prefer? Sugar, honey or DATES… with me",
"You know what will suit you the best? My surname",
" Are you using a photo editing app? ‘Coz every time I look at you, everything else blurs out",
"Do you like shopping? Coz I’m offering 100% discount on me ",
"You’ve got something on your face, let me get it for you. Oh wait, that’s just cuteness. My bad.",
"If you were a pill,I'd overdose",
"Iam so good at algebra that I could replace your X and you would not even know Y ",
"Im not feeling myself today,can I feel you",
"They say Disneyland is the happiest place on earth. Well apparently, no one has ever been standing next to you.",
"Is your dad a terrorist? Cause you’re the bomb.",
"Hey, you’re pretty and I’m cute. Together we’d be Pretty Cute",
"If nothing lasts forever, will you be my nothing?",
"My buddies bet me that I wouldn’t be able to start a conversation with the hottest person in the bar. Wanna buy some drinks with their money?",
"Is it hot in here or is it just you?"]
